### ISSUE TITLE
Item translations aren't reloaded after lang switching

### ISSUE THREAD

**Issue by a-drew** [plank/laravel-media-manager#99]
1. when opening the sidepanel and updating a value in english and then saving 
2. if you toggle to french and then toggle back to english you dont end having the most update to date value

_Originally posted by @nasouh94 in https://github.com/plank/laravel-media-manager/pull/95#pullrequestreview-1108066670_

**Comment by a-drew** [comment]
@nasouh94 does it cache it somewhere in the frontend or does it make an api request on every toggle?

**Comment by rileymcmaster** [comment]
@a-drew even if you close the MM and reopen it, it will display the old value so it is being cached in the MM somewhere. It is not doing an API request on every toggle but maybe it can just make sure to update the cached object once changes have been submitted

**Comment by nasouh94** [comment]
@rileymcmaster @a-drew if i remember correctly a request only fires on page load thats why closing the MM wouldn't do much. I think you're approach Riley with updating the object based on the response of the submission request might the way to go.
